-- kalau udah ke auto increment pakein ini DBCC CHECKIDENT ('departemen', RESEED, 0);

INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('FISIKA', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('MATEMATIKA', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('STATISTIKA', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('KIMIA', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('BIOLOGI', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK MESIN', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK ELEKTRO', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK KIMIA', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK FISIKA', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK INDUSTRI', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK MATERIAL', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK SIPIL', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('ARSITEKTUR', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK LINGKUNGAN', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK GEOMATIKA', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('PERENCANAAN WILAYAH DAN KOTA', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK PERKAPALAN', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK KELAUTAN', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK SISTEM PERKAPALAN', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK INFORMATIKA', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('SISTEM INFORMASI', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('DESAIN PRODUK INDUSTRI', '4 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK TRANSPORTASI LAUT', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEK. SIST PERKAPALAN (GLR GANDA ITS-JERMAN)', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK KOMPUTER', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK GEOFISIKA', '3 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('DESAIN INTERIOR', '4 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK BIOMEDIK', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('SAINS AKTUARIA', '1 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNOLOGI INFORMASI', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('DESAIN KOMUNIKASI VISUAL', '4 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK LEPAS PANTAI', '6 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK PANGAN', '2 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNIK TELEKOMUNIKASI', '5 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('TEKNOLOGI KEDOKTERAN', '7 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('SAINS ANALITIK DAN INSTRUMENTASI KIMIA', '1');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('MANAJEMEN BISNIS', '4 ');
INSERT INTO departemen (namaDepartemen, fakultasID ) VALUES ('STUDI PEMBANGUNAN', '4 ');

select * from departemen